services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: tiles-mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_mongo_username
      MONGO_INITDB_ROOT_PASSWORD: your_secure_mongo_password
      MONGO_INITDB_DATABASE: tiles
    volumes:
      - mongodb_data:/data/db
    networks:
      - tiles-network

  # Tiles application
  tiles-app:
    build: .
    container_name: tiles-app-prod
    restart: always
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://your_mongo_username:your_secure_mongo_password@mongodb:27017/tiles?authSource=admin
      - JWT_SECRET=your_very_long_secure_jwt_secret_key_minimum_32_characters
      - PORT=3000
      - BASE_URL=your-domain.com
      - DOMAIN=your-domain.com
      - EMAIL=admin@your-domain.com
    ports:
      - "80:3000"
      - "443:3000"
    depends_on:
      - mongodb
    volumes:
      - ./greenlock.d:/app/greenlock.d
      - /app/node_modules
    networks:
      - tiles-network

volumes:
  mongodb_data:

networks:
  tiles-network:
    driver: bridge
